variable1=false;
variable2=true;
variable3=0
variable4=1
variable5="0"
variable6="000"
variable7="1"
variable8=NaN
variable9=Infinity
variable10=-Infinity
variable11=""
variable12="20"
variable13="twenty"
variable14=null
variable15=undefined

console.log(typeof(variable1));
console.log(typeof(variable2));
console.log(typeof(variable3));
console.log(typeof(variable4));
console.log(typeof(variable5));
console.log(typeof(variable6));
console.log(typeof(variable7));
console.log(typeof(variable8));
console.log(typeof(variable9));
console.log(typeof(variable10));
console.log(typeof(variable11));
console.log(typeof(variable12));
console.log(typeof(variable13));
console.log(typeof(variable14));
console.log(typeof(variable15));
